Iter5
Alheor/shorturl pull request #5
Opened 2023-10-07 10:07 UTC by Alheor

2023-10-10 20:49 UTC, vovean requested changes

2023-10-10 20:49 UTC, vovean commented on cmd/shortener/main.go
> +	urlMap[shortName] = reqURL
хм а как хранить несколько разных укороченных урлов...

они друг друга перезаписывать будут, получается

2023-10-10 20:49 UTC, vovean commented on cmd/shortener/main.go
> +		http.Error(w, `Request body is empty`, http.StatusBadRequest)
тут ошибка может быть связана не только с пустым телом запроса, а, например, с сетевыми проблемами

тогда твое сообщение, которое ты записываешь в w будет некорректным

2023-10-10 20:49 UTC, vovean commented on cmd/shortener/main_test.go
> +	tests := []test{
классно, что используешь табличные тесты!

2023-10-10 20:49 UTC, vovean commented on internal/config/config_test.go
> +package config
круто, что сделал тесты на конфиг! редко такое вижу

2023-10-10 20:49 UTC, vovean commented on cmd/shortener/main.go
> +var urlMap = make(map[string]string)
было бы круто использовать паттерн репозиторий и сделать кастомный тип, который скрывал бы под собой мапу

2023-10-10 20:49 UTC, vovean commented on cmd/shortener/main.go
> +var urlMap = make(map[string]string)
это поможет в будущем при внедрении другой базы данных

2023-10-11 08:36 UTC, Alheor commented on cmd/shortener/main.go
> +var urlMap = make(map[string]string)
Я пока сделал максимально по простецки. А репу хотел добавить когда непосредственно дело коснется БД.
Если все же, необходимо добавить репозиторий сейчас, то сделаю сейчас. Это необходимо?

2023-10-11 08:43 UTC, Alheor commented on cmd/shortener/main.go
> +	urlMap[shortName] = reqURL
В текущей реализации именно так, т.к. shortName константа. В задании я не увидел ничего связанного с тем, как именно сокращать url, поэтому, по сути, данный код, работает только с 1 url. Согласен, это странно.
Но, в отсутствии какой-либо информации о сокращении этих url, решил, что для первого спринта так и задумано.
Если это не так, и я что-то просмотрел, тогда подскажите каким алгоритмом(или, может, мне самому нужно решить?) сокращаться url и я допилю.

2023-10-14 11:18 UTC, vovean requested changes

2023-10-14 14:32 UTC, vovean requested changes

2023-10-14 14:32 UTC, vovean commented on internal/repository/map_repository.go
> +	defer sn.Unlock()
вот этот мьютекс нужно лочить еще выше, потому что выше у тебя происходит доступ на чтение

так что выше - rlock, runlock, а тут обычный lock, unlock

2023-10-14 14:32 UTC, vovean commented on internal/repository/repository.go
> +type Repository interface {
вижу, ты перенес это в отдельный файл

но это нет. Почитай про то, как устроены в го пакеты и модули. Пакет у тебя написан на первой строке файла (package XXX) и от переноса интерфейса в отдельный файл package не поменялся&

Попробуй перенести интерфйес в тот пакет где используется экземпляр интерфейса

2023-10-18 20:18 UTC, vovean approved these changes

2023-10-20 08:52 UTC, merged